Areas/Store/Pages/ManageSubProduct/AddStepOneSubProduct/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Jovera.Data;
using Jovera.Models;
using Jovera.DataTables;
using NToastNotify;
using System.Linq.Dynamic.Core;
using System.Drawing.Imaging;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;

namespace Jovera.Areas.Store.Pages.ManageSubProduct.AddStepOneSubProduct
{
    public class IndexModel : PageModel
    {
        private CRMDBContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly IToastNotification _toastNotification;
        private readonly UserManager<ApplicationUser> _userManager;
        public string url { get; set; }
        public int notStatictemId { get; set; }
        public static int staticItemId { get; set; }

        [BindProperty]
        public Jovera.Models.SubProductStepOne addStepOne { get; set; }
        public Jovera.Models.SubProductStepOne addStepOneObj { get; set; }

        [BindProperty]
        public DataTablesRequest DataTablesRequest { get; set; }
        public IndexModel(CRMDBContext context, IWebHostEnvironment hostEnvironment,
                                            IToastNotification toastNotification, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
            _toastNotification = toastNotification;
            _userManager = userManager;
            addStepOne = new Jovera.Models.SubProductStepOne();
            addStepOneObj = new Jovera.Models.SubProductStepOne();
        }
        public IActionResult OnGet(int ItemId)
        {
            var ItemExist = _context.Items.Where(e => e.ItemId == ItemId && e.IsDeleted == false && e.HasSubProduct == true).FirstOrDefault();
            if (ItemExist == null)
            {
                Redirect("/Store/PageNotFound");
            }
            staticItemId = ItemId;
            notStatictemId = ItemId;
            url = $"{this.Request.Scheme}://{this.Request.Host}";
            return Page();
        }



      

        public async Task<IActionResult> OnPostAddSubProductStepOne(IFormFile file)
        {

            try
            {
                var supbProdStepOneExist = _context.SubProductStepOnes.Where(e => e.ItemId == staticItemId && e.StepOneId == addStepOne.StepOneId).FirstOrDefault();
                if (supbProdStepOneExist != null)
                {
                    _toastNotification.AddErrorToastMessage("Already Exists");
                    return Redirect($"/Store/ManageSubProduct/AddStepOneSubProduct/index?ItemId={staticItemId}");
                }
                if (file != null)
                {
                    string folder = "Images/Item/";
                    addStepOne.Icon = UploadImage(folder, file);
                }
                addStepOne.ItemId = staticItemId;
                _context.SubProductStepOnes.Add(addStepOne);
                _context.SaveChanges();
                _toastNotification.AddSuccessToastMessage("Added Successfully");
            }
            catch (Exception)
            {

                _toastNotification.AddErrorToastMessage("Something went wrong");
            }
            return Redirect($"/Store/ManageSubProduct/AddStepOneSubProduct/index?ItemId={staticItemId}");
        }
        //public IActionResult OnGetSingleStepOneForEdit(int StepOneId)
        //{
        //    addStepOne = _context.SubProductStepOnes.Where(c => c.SubProductStepOneId == StepOneId).FirstOrDefault();

        //    return new JsonResult(addStepOne);
        //}
        //public async Task<IActionResult> OnPostEditStepOne(int StepOneId)
        //{

        //    try
        //    {
        //        var model = _context.StepOnes.Where(c => c.StepOneId == StepOneId).FirstOrDefault();
        //        if (model == null)
        //        {
        //            _toastNotification.AddErrorToastMessage("Object Not Found");

        //            return Redirect("/crm/configurations/Managesubproduct/managestepone/index");
        //        }
        //        model.StepOneTLAR = addStepOne.StepOneTLAR;
        //        model.StepOneTLEN = addStepOne.StepOneTLEN;
        //        var UpdatedStepOne = _context.StepOnes.Attach(model);

        //        UpdatedStepOne.State = Microsoft.EntityFrameworkCore.EntityState.Modified;

        //        _context.SaveChanges();

        //        _toastNotification.AddSuccessToastMessage("Edited Successfully");



        //    }
        //    catch (Exception)
        //    {
        //        _toastNotification.AddErrorToastMessage("Something went Error");

        //    }
        //    return Redirect("/crm/configurations/Managesubproduct/managestepone/index");
        //}
        //public IActionResult OnGetSingleStepOneForView(int StepOneId)
        //{
        //    var Result = _context.StepOnes.Where(c => c.StepOneId == StepOneId).FirstOrDefault();
        //    return new JsonResult(Result);
        //}
        //public IActionResult OnGetSingleStepOneForDelete(int StepOneId)
        //{
        //    var Result = _context.StepOnes.Where(c => c.StepOneId == StepOneId).FirstOrDefault();
        //    return new JsonResult(Result);
        //}
        //public async Task<IActionResult> OnPostDeleteStepOne(int StepOneId)
        //{
        //    try
        //    {
        //        var model = _context.StepOnes.Where(c => c.StepOneId == StepOneId).FirstOrDefault();
        //        if (model == null)
        //        {
        //            _toastNotification.AddErrorToastMessage("Object Not Found");

        //            return Redirect("/crm/configurations/Managesubproduct/managestepone/index");
        //        }
        //        model.IsDeleted = true;
        //        var UpdatedStepOne = _context.StepOnes.Attach(model);

        //        UpdatedStepOne.State = Microsoft.EntityFrameworkCore.EntityState.Modified;

        //        _context.SaveChanges();

        //        _toastNotification.AddSuccessToastMessage("Step Deleted Successfully");



        //    }
        //    catch (Exception)
        //    {
        //        _toastNotification.AddErrorToastMessage("Something went Error");

        //    }

        //    return Redirect("/crm/configurations/Managesubproduct/managestepone/index");

        //}

        private string UploadImage(string folderPath, IFormFile file)
        {

            folderPath += Guid.NewGuid().ToString() + "_" + file.FileName;

            string serverFolder = Path.Combine(_hostEnvironment.WebRootPath, folderPath);

            file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));

            return folderPath;
        }

    }
}

Areas/Store/Pages/ManageSubProduct/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Jovera.Data;
using Jovera.Models;
using Jovera.DataTables;
using NToastNotify;
using QRCoder;
using System.Drawing;
using System.Linq.Dynamic.Core;
using System.Diagnostics.Eventing.Reader;
using System.Drawing.Imaging;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Jovera.ViewModels;

namespace Jovera.Areas.Store.Pages.ManageSubProduct
{
    public class IndexModel : PageModel
    {
		private CRMDBContext _context;
		private readonly IWebHostEnvironment _hostEnvironment;
		private readonly IToastNotification _toastNotification;
		private readonly UserManager<ApplicationUser> _userManager;

		public string QRScan { get; set; }
		public string url { get; set; }
		public string QRCodeText { get; set; }
        public List<StepTwo> StepTwosList = new List<StepTwo>();

        [BindProperty]
		public AddSubProductVm addSubProduct { get; set; }


		
		public static int staticStepOneSubProdId = 0;
		public static int staticStepOneId = 0;
		public static int staticItemIdForUpdateStatus = 0;
       // [BindProperty]
        public MiniSubProduct addSubProductObj { get; set; }
		
		[BindProperty]
		public DataTablesRequest DataTablesRequest { get; set; }
		public IndexModel(CRMDBContext context, IWebHostEnvironment hostEnvironment,
											IToastNotification toastNotification, UserManager<ApplicationUser> userManager)
		{
			_context = context;
			_hostEnvironment = hostEnvironment;
			_toastNotification = toastNotification;
			_userManager = userManager;
			addSubProduct = new AddSubProductVm();
            addSubProductObj = new MiniSubProduct();
		}
		public void OnGet(int stepOneSubProductId)
		{
			var SubProductStepObj = _context.SubProductStepOnes.Where(e=>e.SubProductStepOneId== stepOneSubProductId&&e.IsDeleted==false).FirstOrDefault();
			if (SubProductStepObj == null)
			{
				Redirect("/PageNotFound");
			}
            
            staticStepOneSubProdId = stepOneSubProductId;
			url = $"{this.Request.Scheme}://{this.Request.Host}";
            addSubProduct.SubProductStepOneId =staticStepOneSubProdId;
            addSubProduct.StepOneId = SubProductStepObj.StepOneId;
            staticStepOneId = SubProductStepObj.StepOneId;
            staticItemIdForUpdateStatus = SubProductStepObj.ItemId;
            //StepTwosList = _context.StepTwos.Where(e => e.StepOneId == SubProductStepObj.StepOneId&&e.IsDeleted==false).ToList();

        }

		

		public async Task<JsonResult> OnPostAsync()
		{
			

			var recordsTotal = _context.MiniSubProducts.Where(e => e.SubProductStepOneId == staticStepOneSubProdId&&e.IsDeleted==false).Count();

			var customersQuery = _context.MiniSubProducts.Include(e=>e.StepTwo).Include(e=>e.SubProductStepOne).ThenInclude(e=>e.StepOne).Where(e => e.SubProductStepOneId == staticStepOneSubProdId&&e.IsDeleted == false).Select(i => new
			{
                MiniSubProductId = i.MiniSubProductId,
                IsDeleted = i.IsDeleted,
                ItemQRCode = i.ItemQRCode,
                StepOneTLAR = i.SubProductStepOne.StepOne.StepOneTLAR,
                StepOneTLEN = i.SubProductStepOne.StepOne.StepOneTLEN,
                SubProductStepOneId = i.SubProductStepOneId,
                StepTwoTLAR = i.StepTwo.StepTwoTLAR,
                StepTwoTLEN = i.StepTwo.StepTwoTLEN,
				Quantity = i.Quantity,
			}).AsQueryable();


			var searchText = DataTablesRequest.Search.Value?.ToUpper();
			if (!string.IsNullOrWhiteSpace(searchText))
			{
				customersQuery = customersQuery.Where(s =>
					s.StepTwoTLEN.ToUpper().Contains(searchText) ||
					s.StepTwoTLAR.ToUpper().Contains(searchText)
				);
			}

			var recordsFiltered = customersQuery.Count();

			var sortColumnName = DataTablesRequest.Columns.ElementAt(DataTablesRequest.Order.ElementAt(0).Column).Name;
			var sortDirection = DataTablesRequest.Order.ElementAt(0).Dir.ToLower();

			// using System.Linq.Dynamic.Core
			customersQuery = customersQuery.OrderBy($"{sortColumnName} {sortDirection}");

			var skip = DataTablesRequest.Start;
			var take = DataTablesRequest.Length;
			var data = await customersQuery
				.Skip(skip)
				.Take(take)
				.ToListAsync();

			return new JsonResult(new
			{
				draw = DataTablesRequest.Draw,
				recordsTotal = recordsTotal,
				recordsFiltered = recordsFiltered,
				data = data
			});
		}
        public IActionResult OnGetSingleMiniSubProductForView(int MiniSubProductId)
        {
            var Result = _context.MiniSubProducts.Include(e=>e.StepTwo).Include(e=>e.SubProductStepOne).ThenInclude(e=>e.StepOne).Where(c => c.MiniSubProductId == MiniSubProductId).Select(i => new
            {
                ItemQRCode= i.ItemQRCode,
                StepTwoTLAR = i.StepTwo.StepTwoTLAR,
                StepTwoTLEN = i.StepTwo.StepTwoTLEN,
                StepOneTLAR = i.SubProductStepOne.StepOne.StepOneTLAR,
                StepOneTLEN = i.SubProductStepOne.StepOne.StepOneTLEN,
                Quantity = i.Quantity,
            }).FirstOrDefault();
            return new JsonResult(Result);
        }
        public IActionResult OnGetSingleMiniSubProductForEdit(int MiniSubProductId)
        {
            var MiniSubProduct = _context.MiniSubProducts.Where(c => c.MiniSubProductId == MiniSubProductId).FirstOrDefault();
            addSubProduct.Quantity = MiniSubProduct.Quantity;
            addSubProduct.StepTwoId = MiniSubProduct.StepTwoId;
            addSubProduct.SubProductStepOneId = MiniSubProduct.SubProductStepOneId;
            addSubProduct.MiniSubProductId = MiniSubProduct.MiniSubProductId;
            addSubProduct.StepOneId = staticStepOneId;
            return new JsonResult(addSubProduct);
        }
        public async Task<IActionResult> OnPostEditSubProduct(int MiniSubProductId)
        {

            try
            {
                var model = _context.MiniSubProducts.Where(c => c.MiniSubProductId == MiniSubProductId).FirstOrDefault();
                if (model == null)
                {
                    _toastNotification.AddErrorToastMessage("Object Not Found");

                    return Redirect($"/Store/ManageSubProduct/Index?stepOneSubProductId={staticStepOneSubProdId}");

                }
                model.Quantity = addSubProduct.Quantity;
                model.StepTwoId = addSubProduct.StepTwoId;
                //model.MiniSubProductId = addSubProduct.MiniSubProductId;
                //model.SubProductStepOneId = addSubProduct.SubProductStepOneId;
                var UpdatedMiniSubProduct = _context.MiniSubProducts.Attach(model);

                UpdatedMiniSubProduct.State = Microsoft.EntityFrameworkCore.EntityState.Modified;

                _context.SaveChanges();

                _toastNotification.AddSuccessToastMessage("Sub Product Edited Successfully");



            }
            catch (Exception)
            {
                _toastNotification.AddErrorToastMessage("Something went Error");

            }
            return Redirect($"/Store/ManageSubProduct/Index?stepOneSubProductId={staticStepOneSubProdId}");
        }
        public IActionResult OnGetSingleMiniSubProductForDelete(int MiniSubProductId)
        {
            var Result = _context.MiniSubProducts.Where(c => c.MiniSubProductId == MiniSubProductId).FirstOrDefault();
            return new JsonResult(Result);
        }
        public async Task<IActionResult> OnPostDeleteSubProduct(int MiniSubProductId)
        {
            try
            {
                var model = _context.MiniSubProducts.Where(c => c.MiniSubProductId == MiniSubProductId).FirstOrDefault();
                if (model == null)
                {
                    _toastNotification.AddErrorToastMessage("Object Not Found");

                    return Redirect($"/Store/ManageSubProduct/Index?stepOneSubProductId={staticStepOneSubProdId}");

                }
                model.IsDeleted = true;
                var UpdatedMini = _context.MiniSubProducts.Attach(model);

                UpdatedMini.State = Microsoft.EntityFrameworkCore.EntityState.Modified;

                _context.SaveChanges();

                _toastNotification.AddSuccessToastMessage("Sub Product Deleted Successfully");



            }
            catch (Exception)
            {
                _toastNotification.AddErrorToastMessage("Something went Error");

            }

            return Redirect($"/Store/ManageSubProduct/Index?stepOneSubProductId={staticStepOneSubProdId}");


        }
        public async Task<IActionResult> OnPostAddSubProduct()
        {

            try
            {
				var existedSubProduct = _context.MiniSubProducts.Where(e => e.StepTwoId ==addSubProduct.StepTwoId && e.SubProductStepOneId ==staticStepOneSubProdId&&e.IsDeleted==false).FirstOrDefault();
				if (existedSubProduct != null)
				{
                    _toastNotification.AddErrorToastMessage("SubProduct in Already Exist Before,Can Update In Its Quantity");
                    return Redirect($"/Store/ManageSubProduct/Index?stepOneSubProductId={staticStepOneSubProdId}");
                }
                //var user = await _userManager.GetUserAsync(User);
                //if (user == null)
                //{
                //    return Redirect("/Login");

                //}
                //var vendor = _context.Stores.Where(e => e.Email == user.Email).FirstOrDefault();
                //if (vendor == null)
                //{
                //    return Redirect("/Login");
                //}
                var addMiniSub = new MiniSubProduct()
                {
                    Quantity= addSubProduct.Quantity,
                    StepTwoId=addSubProduct.StepTwoId,
                    SubProductStepOneId=staticStepOneSubProdId


                };
				
                _context.MiniSubProducts.Add(addMiniSub);
                _context.SaveChanges();
                 GenerateBarCode(addMiniSub.MiniSubProductId);
                

Areas/Store/Pages/ManageSubProduct/_AddPopup.cshtml
@using Jovera.Data
@inject CRMDBContext _context
@{
    var firstStepList = _context.Colors.Select(e => new { e.ColorId, e.ColorTLAR,e.ColorTLEN });
    var secondStepList = _context.Sizes.Select(e => new { e.SizeId, e.SizeTLAR,e.SizeTLEN });
    var locale = Context.Request.HttpContext.Features.Get<IRequestCultureFeature>();
    var BrowserCulture = locale.RequestCulture.UICulture.ToString();
}
@model Jovera.Models.SubProduct

<div class="modal fade" id="AddModal" tabindex="-1" aria-labelledby="AddModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

            <div class="modal-header bg-light p-3">
                <h5 class="modal-title" id="exampleModalLabel">@sharedResource["Add SubProduct"]</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" id="close-modal"></button>
            </div>

            <form asp-area="Store" asp-page="/ManageSubProduct/Index" asp-page-handler="AddSubProduct" enctype="multipart/form-data" onsubmit="return validateMyForm();">
                <div class="modal-body">
                    <input type="text" hidden value="@Model.ItemId"  />
                    <div class="row g-3">
   

                        <div class="col-lg-12">
                            <label asp-for="@Model.ColorId" for="car-rental-name">@sharedResource["Step One"] <small class="text-danger">*</small></label>

                            <select data-val="true" data-val-required="@sharedResource["Please choose a Step One"]" id="catId" asp-for="@Model.ColorId" class="form-select required" aria-label="Default select example" required>
                                <option selected value="Select Type">@sharedResource["Select Step One"]</option>

                                @{
                                    if (firstStepList != null)
                                    {
                                        foreach (var item in @firstStepList)

                                        {
                                             if (BrowserCulture == "en-US")
                                            {

                                                <option value="@item.ColorId">@item.ColorTLEN</option>
                                            }else{
                                                <option value="@item.ColorId">@item.ColorTLAR</option>

                                            }
                                        }
                                    }
                                }

                            </select>

                            <span asp-validation-for="@Model.ColorId" class="text-alert"></span>
                        </div>

                        <div class="col-lg-12">
                            <label asp-for="@Model.SizeId" for="car-rental-name">@sharedResource["Step Two"] <small class="text-danger">*</small></label>

                            <select data-val="true" data-val-required="@sharedResource["Please choose a Step Two"]" id="catId" asp-for="@Model.SizeId" class="form-select required" aria-label="Default select example" required>
                                <option selected value="Select Type">@sharedResource["Select Step Two"]</option>

                                @{
                                    if (secondStepList != null)
                                    {
                                        foreach (var item in @secondStepList)

                                        {
                                            if (BrowserCulture == "en-US")
                                            {

                                                <option value="@item.SizeId">@item.SizeTLEN</option>
                                            }
                                            else
                                            {
                                                <option value="@item.SizeId">@item.SizeTLAR</option>

                                            }
                                        }
                                    }
                                }

                            </select>

                            <span asp-validation-for="@Model.SizeId" class="text-alert"></span>
                        </div>
                        <div class="col-lg-12" id="itemQuaintityId">
                            <div>
                                <label for="@Model.Quantity" class="form-label">@sharedResource["Quantity"]</label>
                                <input type="number" min="1" asp-for="@Model.Quantity" id="company_name-field" class="form-control" placeholder="@sharedResource["Enter Quantity"]" />
                                <span asp-validation-for="@Model.Quantity" class="text-danger"></span>
                            </div>
                        </div>
                       
                    </div>
                    <!--end row-->
                </div>
         
                <div class="modal-footer">
                    <div class="hstack gap-2 justify-content-end">
                        <button type="button" class="btn btn-light" data-bs-dismiss="modal">@sharedResource["Close"]</button>
                        <button class="btn btn-success" id="add-btn">@sharedResource["Add SubProduct"]</button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>

Areas/Store/Pages/ManageSubProduct/_DatchDelete.cshtml
@{
}
@model Jovera.ViewModels.AddSubProductVm

<div class="modal fade zoomIn" id="deleteRecordModal" tabindex="-1"
     aria-labelledby="deleteRecordLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="btn-close" data-bs-dismiss="modal"
                        aria-label="Close" id="btn-close"></button>
            </div>
            <div class="modal-body p-5 text-center">
                <lord-icon src="https://cdn.lordicon.com/gsqxdxog.json"
                           trigger="loop" colors="primary:#405189,secondary:#f06548"
                           style="width:90px;height:90px"></lord-icon>
                <div class="mt-4 text-center">


                    <h4 class="fs-semibold">@sharedResource["You are about to delete This SubProduct One ?"]</h4>
                    <p class="text-muted fs-14 mb-4 pt-1">
                        @sharedResource["Deleting it SubProduct will remove all of its information from its database."]
                    </p>
                    <div class="hstack gap-2 justify-content-center remove">
                        <button class="btn btn-link link-success fw-medium text-decoration-none" id="deleteRecord-close"
                                data-bs-dismiss="modal">
                            @sharedResource["Close"]
                        </button>
                        <form asp-area="Store" asp-page="/ManageSubProduct/Index"  asp-page-handler="DeleteSubProduct" enctype="multipart/form-data">

                            <input asp-for="@Model.MiniSubProductId" id="DeleteMiniSubProductId" hidden>
                            
                            <button class="btn btn-danger" type="submit" id="delete-record">
                                @sharedResource["Yes,"]
                                @sharedResource["Delete It!!"]
                            </button>

                        </form>
                    </div>
                </div>

            </div>


        </div>
    </div>
</div>

Areas/Store/Pages/ManageSubProduct/_EditPopup.cshtml
@using Jovera.ViewModel
@using Jovera.Data
@inject CRMDBContext _context
@{
    var locale = Context.Request.HttpContext.Features.Get<IRequestCultureFeature>();
    var BrowserCulture = locale.RequestCulture.UICulture.ToString();
}
@model Jovera.ViewModels.AddSubProductVm
@{
    var secondStepList = _context.StepTwos.Where(e => e.StepOneId == @Model.StepOneId && e.IsDeleted == false).Select(e => new { e.StepTwoId, e.StepTwoTLAR, e.StepTwoTLEN });

}
<div class="modal fade" id="showEditModal" tabindex="-1"
     aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header bg-light p-3">
                <h5 class="modal-title" id="exampleModalLabel">@sharedResource["Edit Sub Product"]</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"
                        aria-label="Close" id="close-modal"></button>
            </div>

            <form asp-area="Store" asp-page="/ManageSubProduct/Index" asp-page-handler="EditSubProduct" enctype="multipart/form-data" onsubmit="return validateMyForm();">
                <div class="modal-body">
                    <input type="text" id="EMiniSubProductId" hidden value="@Model.MiniSubProductId"  asp-for="@Model.MiniSubProductId" />
                    <input type="text" id="ESubProductStepOneId" hidden value="@Model.SubProductStepOneId" />
                    <div class="row g-3">


                       
                        <div class="col-lg-12">
                            <label asp-for="@Model.StepTwoId" for="car-rental-name">@sharedResource["Step Two"] <small class="text-danger">*</small></label>

                            <select data-val="true" data-val-required="@sharedResource["Please choose a Step Two"]" id="EStepTwoId" asp-for="@Model.StepTwoId" class="form-select required" aria-label="Default select example" required>
                                <option selected value="Select Type">@sharedResource["Select Step Two"]</option>

                                @{
                                    if (secondStepList != null)
                                    {
                                        foreach (var item in @secondStepList)

                                        {
                                            if (BrowserCulture == "en-US")
                                            {

                                                <option value="@item.StepTwoId">@item.StepTwoTLEN</option>
                                            }
                                            else
                                            {
                                                <option value="@item.StepTwoId">@item.StepTwoTLAR</option>

                                            }
                                        }
                                    }
                                }

                            </select>

                            <span asp-validation-for="@Model.StepTwoId" class="text-alert"></span>
                        </div>
                        <div class="col-lg-12" id="itemQuaintityId">
                            <div>
                                <label for="@Model.Quantity" class="form-label">@sharedResource["Quantity"]</label>
                                <input type="number" min="1" asp-for="@Model.Quantity" id="EQuantityId" class="form-control" placeholder="@sharedResource["Enter Quantity"]" />
                                <span asp-validation-for="@Model.Quantity" class="text-danger"></span>
                            </div>
                        </div>

                    </div>
                    <!--end row-->
                </div>

                <div class="modal-footer">
                    <div class="hstack gap-2 justify-content-end">
                        <button type="button" class="btn btn-light" data-bs-dismiss="modal">@sharedResource["Close"]</button>
                        <button class="btn btn-success" id="add-btn">@sharedResource["Edit Sub Product"]</button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>

Areas/Store/Pages/ManageSubProduct/_ViewPopup.cshtml
@model Jovera.ViewModels.AddSubProductVm

<div class="modal fade" id="QuickViewPoup" tabindex="-1"
     aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header bg-light p-3">
                <h5 class="modal-title" id="exampleModalLabel">@sharedResource["Sub Product Details"]</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"
                        aria-label="Close" id="close-modal"></button>
            </div>
            <div class="card mb-3">
                <div class="card-body">
                   
                    <div class="table-card">
                        <table class="table mb-0">
                            <tbody>
                   
                                <tr>
                                <td class="fw-medium">@sharedResource["QRCode"]</td>
                                    <td  >
                                        <img src="" id="DItemQRCodeId" width="200px" height="200px" />
                                    </td>
                                </tr>
                                <tr>
                                <td class="fw-medium">@sharedResource["Step One Arabic Title"]</td>
                                    <td id="DStepOneTLARId"></td>
                                </tr>
                                <tr>
                                <td class="fw-medium">@sharedResource["Step One English Title"]</td>
                                    <td id="DStepOneTLENId"></td>
                                </tr>
                                <tr>
                                <td class="fw-medium">@sharedResource["Step Two Arabic Title"]</td>
                                    <td id="DStepTwoTLARId"></td>
                                </tr>
                                <tr>
                                <td class="fw-medium">@sharedResource["Step Two English Title"]</td>
                                    <td id="DStepTwoTLENId"></td>
                                </tr>
                                <tr>
                                <td class="fw-medium">@sharedResource["Quantity"]</td>
                                    <td id="DQuantityId"></td>
                                </tr>
                               
                               

                            </tbody>
                        </table><!--end table-->
                    </div>
                </div>
            </div><!--end card-->
            <div class="modal-footer">
                <div class="hstack gap-2 justify-content-end">
                    <button type="button" class="btn btn-light"
                            data-bs-dismiss="modal">
                        @sharedResource["Close"]
                    </button>


                </div>
            </div>
        </div>
    </div>
</div>