Areas/Store/Pages/ManageItem/AddItem.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Jovera.Data;
using Jovera.Models;
using NToastNotify;
using QRCoder;
using System.Drawing;
using System.Linq.Dynamic.Core;
using System.Diagnostics.Eventing.Reader;
using System.Drawing.Imaging;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Identity;
using Jovera.ViewModels;

namespace Jovera.Areas.Store.Pages.ManageItem
{
    public class AddItemModel : PageModel
    {
        private CRMDBContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;
        private readonly IToastNotification _toastNotification;
        private readonly UserManager<ApplicationUser> _userManager;
        public string QRScan { get; set; }
        public string url { get; set; }
        public string QRCodeText { get; set; }
        public IRequestCultureFeature locale;
        public string BrowserCulture;

        [BindProperty]
        public Item AddItem { get; set; }
        [BindProperty]
        public AddSubProductVm AddSubProductVm  { get; set; }

        public AddItemModel(CRMDBContext context, IWebHostEnvironment hostEnvironment,
                                            IToastNotification toastNotification,UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
            _toastNotification = toastNotification;
            _userManager = userManager;
            AddItem = new Item();
           
        }
        public async Task<IActionResult> OnGet()
        {
            locale = Request.HttpContext.Features.Get<IRequestCultureFeature>();
            BrowserCulture = locale.RequestCulture.UICulture.ToString();
            url = $"{this.Request.Scheme}://{this.Request.Host}";
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Redirect("/Login");

            }
            var vendor = _context.Stores.Where(e => e.Email == user.Email).FirstOrDefault();
            if (vendor == null)
            {
                return Redirect("/Login");
            }
            AddItem.StoreId = vendor.StoreId;
            return Page();
        }
        public async Task<IActionResult> OnPost(IFormFile file, IFormFileCollection MorePhoto)
        {

            try
            {

                if (file != null)
                {
                    string folder = "Images/Item/";
                    AddItem.ItemImage = UploadImage(folder, file);
                }
                List<ItemImage> itemImagesList = new List<ItemImage>();


                if (MorePhoto.Count != 0)
                {
                    foreach (var item in MorePhoto)
                    {
                        var itemImageObj = new ItemImage();
                        string folder = "Images/Item/";
                        itemImageObj.ImageName = UploadImage(folder, item);
                        itemImagesList.Add(itemImageObj);


                    }
                    AddItem.ItemImages = itemImagesList;
                }
                AddItem.PublishedDate = DateTime.Now;
                AddItem.ItemStatusId = 1;
                

                _context.Items.Add(AddItem);
                _context.SaveChanges();
                if (!AddItem.HasSubProduct)
                {
                    GenerateBarCode(AddItem.ItemId);
                }



            }
            catch (Exception)
            {

                _toastNotification.AddErrorToastMessage("Something went wrong");
            }
            return Redirect("/Store/ManageItem/Index");
        }
        public void GenerateBarCode(int ItemId)
        {
            var Event = _context.Items.Where(e => e.ItemId == ItemId).FirstOrDefault();
            if (Event != null)
            {
                Event.BarCode = ItemId.ToString();

            }
            QRCodeText = $"{this.Request.Scheme}://{this.Request.Host}/?Id=" + ItemId + "&HasSubProd=" + false;
            string QRCodeName = QRCodeText;
            QRCodeGenerator QrGenerator = new QRCodeGenerator();
            QRCodeData QrCodeInfo = QrGenerator.CreateQrCode(QRCodeText, QRCodeGenerator.ECCLevel.Q);
            QRCode QrCode = new QRCode(QrCodeInfo);
            Bitmap QrBitmap = QrCode.GetGraphic(60);
            byte[] BitmapArray = BitmapToByteArray(QrBitmap);
            string uploadFolder = Path.Combine(_hostEnvironment.WebRootPath, "Images/Item");
            string uniqePictureName = Guid.NewGuid() + ".jpeg";
            string uploadedImagePath = Path.Combine(uploadFolder, uniqePictureName);
            using (var imageFile = new FileStream(uploadedImagePath, FileMode.Create))
            {
                imageFile.Write(BitmapArray, 0, BitmapArray.Length);
                imageFile.Flush();
            }
            
            Event.BarCode = "Images/Item/" + uniqePictureName;
            Event.ItemStatusId = 2;
            Event.Quantity = 0;
            var UpdatedEvent = _context.Items.Attach(Event);
            UpdatedEvent.State = Microsoft.EntityFrameworkCore.EntityState.Modified;
            _context.SaveChanges();
            _toastNotification.AddSuccessToastMessage("Item Added Successfully");



        }
        private byte[] BitmapToByteArray(Bitmap bitmap)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                bitmap.Save(ms, ImageFormat.Png);
                return ms.ToArray();
            }
        }
        private string UploadImage(string folderPath, IFormFile file)
        {

            folderPath += Guid.NewGuid().ToString() + "_" + file.FileName;

            string serverFolder = Path.Combine(_hostEnvironment.WebRootPath, folderPath);

            file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));

            return folderPath;
        }

    }
}

Areas/Store/Pages/ManageItem/EditItem.cshtml.cs
using Jovera.Data;
using Jovera.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NToastNotify;
using Microsoft.AspNetCore.Localization;
using Microsoft.Extensions.Hosting;

namespace Jovera.Areas.Store.Pages.ManageItem
{
    public class EditItemModel : PageModel
    {
        private CRMDBContext _context;
        private readonly IToastNotification _toastNotification;
        public IRequestCultureFeature locale;
        public string BrowserCulture;
        public string url { get; set; }
        private readonly IWebHostEnvironment _hostEnvironment;
        [BindProperty]
        public Item EditItem { get; set; }


        public EditItemModel(CRMDBContext context, IToastNotification toastNotification, IWebHostEnvironment hostEnvironment)
        {
            _hostEnvironment = hostEnvironment;
            _context = context;
            _toastNotification = toastNotification;
        }


        public IActionResult OnGet(int ItemId)
        {
            locale = Request.HttpContext.Features.Get<IRequestCultureFeature>();
            BrowserCulture = locale.RequestCulture.UICulture.ToString();
            url = $"{this.Request.Scheme}://{this.Request.Host}";
            EditItem = _context.Items.Include(e=>e.ItemImages).FirstOrDefault(a => a.ItemId == ItemId);
            if (EditItem.ItemStatusId==3)
            {
                return Redirect($"/Store/ManageItem/ProductDetails?ItemId={EditItem.ItemId}");
            }
            return Page();
        }
        public async Task<IActionResult> OnPost(int ItemId, IFormFile file, IFormFileCollection Editfilepond)
        {
            try
            {

                var DbItem = _context.Items.Where(c => c.ItemId == ItemId).FirstOrDefault();

                if (DbItem == null)
                {
                    _toastNotification.AddErrorToastMessage("Item Not Found");

                    return Redirect("/Store/ManageItem/Index");
                }
                if (file != null)
                {


                    string folder = "Images/Item/";

                    DbItem.ItemImage = UploadImage(folder, file);
                }
                else
                {
                    DbItem.ItemImage = EditItem.ItemImage;
                }

                List<ItemImage> EditItemImagesList = new List<ItemImage>();

                if (Editfilepond.Count != 0)
                {

                    

                    foreach (var item in Editfilepond)
                    {

                        var itemImageObj = new ItemImage();
                        string folder = "Images/Item/";
                        itemImageObj.ImageName = UploadImage(folder, item);
                        itemImageObj.ItemId = ItemId;
                        EditItemImagesList.Add(itemImageObj);


                    }
                    _context.ItemImages.AddRange(EditItemImagesList);
                }

                DbItem.ItemTitleAr = EditItem.ItemTitleAr;
                DbItem.ItemTitleEn = EditItem.ItemTitleEn;
                DbItem.ItemMiniDetailsAr = EditItem.ItemMiniDetailsAr;
                DbItem.ItemMiniDetailsEn = EditItem.ItemMiniDetailsEn;
                DbItem.ItemDescriptionAr = EditItem.ItemDescriptionAr;
                DbItem.ItemDescriptionEn = EditItem.ItemDescriptionEn;
                //DbItem.IsActive = EditItem.IsActive;
                DbItem.OrderIndex = EditItem.OrderIndex;
                DbItem.VideoUrl = EditItem.VideoUrl;
                DbItem.OurSellingPrice = EditItem.OurSellingPrice;
                DbItem.SellingPriceForCustomer = EditItem.SellingPriceForCustomer;
                DbItem.MiniSubCategoryId = EditItem.MiniSubCategoryId;
                DbItem.HasSubProduct = EditItem.HasSubProduct;
                var UpdatedItem = _context.Items.Attach(DbItem);
                UpdatedItem.State = Microsoft.EntityFrameworkCore.EntityState.Modified;

                _context.SaveChanges();

                _toastNotification.AddSuccessToastMessage("Item Edited successfully");


            }
            catch (Exception)
            {
                _toastNotification.AddErrorToastMessage("Something went Error");

            }
            return Redirect("/Store/ManageItem/Index");
        }



        private string UploadImage(string folderPath, IFormFile file)
        {

            folderPath += Guid.NewGuid().ToString() + "_" + file.FileName;

            string serverFolder = Path.Combine(_hostEnvironment.WebRootPath, folderPath);

            file.CopyToAsync(new FileStream(serverFolder, FileMode.Create));

            return folderPath;
        }
    }
}

Areas/Store/Pages/ManageItem/ProductDetails.cshtml.cs
using Jovera.Data;
using Jovera.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NToastNotify;
using Microsoft.AspNetCore.Localization;
using Microsoft.Extensions.Hosting;

namespace Jovera.Areas.Store.Pages.ManageItem
{
    public class ProductDetailsModel : PageModel
    {
        private CRMDBContext _context;
        private readonly IToastNotification _toastNotification;
        public IRequestCultureFeature locale;
        public string BrowserCulture;
        public string url { get; set; }
        private readonly IWebHostEnvironment _hostEnvironment;
        [BindProperty]
        public Item ItemDetails { get; set; }
        public int AvailableQuantityInStore = 0;

        public ProductDetailsModel(CRMDBContext context, IToastNotification toastNotification, IWebHostEnvironment hostEnvironment)
        {
            _hostEnvironment = hostEnvironment;
            _context = context;
            _toastNotification = toastNotification;
        }


        public IActionResult OnGet(int ItemId)
        {
            locale = Request.HttpContext.Features.Get<IRequestCultureFeature>();
            BrowserCulture = locale.RequestCulture.UICulture.ToString();
            url = $"{this.Request.Scheme}://{this.Request.Host}";
            ItemDetails = _context.Items.Include(e => e.ItemImages).Include(e=>e.MiniSubCategory).Include(e => e.SubProducts).ThenInclude(e=>e.StepOne).ThenInclude(e=>e.StepTwos).FirstOrDefault(a => a.ItemId == ItemId);
            if (ItemDetails.HasSubProduct)
            {
                AvailableQuantityInStore = _context.SubProducts.Where(e => e.ItemId == ItemId).Sum(e => e.Quantity.Value);

			}
            else
            {
                AvailableQuantityInStore = ItemDetails.Quantity;

			}
            return Page();
        }
        public IActionResult OnGetSingleUpdateItemQuantityForEdit(int ItemId)
        {
            var item = _context.Items.Where(c => c.ItemId == ItemId).FirstOrDefault();

            return new JsonResult(item);
        }
        public async Task<IActionResult> OnPostUpdateItemQuantity(int ItemId)
        {

            try
            {
                var model = _context.Items.Where(c => c.ItemId == ItemId).FirstOrDefault();
                if (model == null)
                {
                    _toastNotification.AddErrorToastMessage("Item Not Found");
                    return Page();
                    
                }


               

                model.Quantity = ItemDetails.Quantity;
                


                var UpdatedItem = _context.Items.Attach(model);

                UpdatedItem.State = Microsoft.EntityFrameworkCore.EntityState.Modified;

                _context.SaveChanges();

                _toastNotification.AddSuccessToastMessage("Item Edited successfully");

                return Redirect($"/Store/ManageItem/ProductDetails?ItemId={ItemId}");

            }
            catch (Exception)
            {
                _toastNotification.AddErrorToastMessage("Something went Error");

            }
            return Redirect($"/Store/ManageItem/ProductDetails?ItemId={ItemDetails.ItemId}");
        }

    }
}

Areas/Store/Pages/ManageItem/_AddPopup.cshtml
@using Jovera.Data
@inject CRMDBContext _context
@{
    var firstStepList = _context.StepOnes.Select(e => new { e.StepOneId, e.StepOneTLAR,e.StepOneTLEN });
    var secondStepList = _context.StepTwos.Select(e => new { e.StepTwoId, e.StepTwoTLAR,e.StepTwoTLEN });
    var locale = Context.Request.HttpContext.Features.Get<IRequestCultureFeature>();
    var BrowserCulture = locale.RequestCulture.UICulture.ToString();
}
@model Jovera.Models.SubProduct

<div class="modal fade" id="AddModal" tabindex="-1" aria-labelledby="AddModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">

            <div class="modal-header bg-light p-3">
                <h5 class="modal-title" id="exampleModalLabel">@sharedResource["Add SubProduct"]</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" id="close-modal"></button>
            </div>

            <form asp-area="Store" asp-page="/ManageSubProduct/Index" asp-page-handler="AddSubProduct" enctype="multipart/form-data" onsubmit="return validateMyForm();">
                <div class="modal-body">
                    <input type="text" hidden value="@Model.ItemId"  />
                    <div class="row g-3">
   

                        <div class="col-lg-12">
                            <label asp-for="@Model.StepOneId" for="car-rental-name">@sharedResource["Step One"] <small class="text-danger">*</small></label>

                            <select data-val="true" data-val-required="@sharedResource["Please choose a Step One"]" id="catId" asp-for="@Model.StepOneId" class="form-select required" aria-label="Default select example" required>
                                <option selected value="Select Type">@sharedResource["Select Step One"]</option>

                                @{
                                    if (firstStepList != null)
                                    {
                                        foreach (var item in @firstStepList)

                                        {
                                             if (BrowserCulture == "en-US")
                                            {

                                                <option value="@item.StepOneId">@item.StepOneTLEN</option>
                                            }else{
                                                <option value="@item.StepOneId">@item.StepOneTLAR</option>

                                            }
                                        }
                                    }
                                }

                            </select>

                            <span asp-validation-for="@Model.StepOneId" class="text-alert"></span>
                        </div>

                        <div class="col-lg-12">
                            <label asp-for="@Model.StepTwoId" for="car-rental-name">@sharedResource["Step Two"] <small class="text-danger">*</small></label>

                            <select data-val="true" data-val-required="@sharedResource["Please choose a Step Two"]" id="catId" asp-for="@Model.StepTwoId" class="form-select required" aria-label="Default select example" required>
                                <option selected value="Select Type">@sharedResource["Select Step Two"]</option>

                                @{
                                    if (secondStepList != null)
                                    {
                                        foreach (var item in @secondStepList)

                                        {
                                            if (BrowserCulture == "en-US")
                                            {

                                                <option value="@item.StepTwoId">@item.StepTwoTLEN</option>
                                            }
                                            else
                                            {
                                                <option value="@item.StepTwoId">@item.StepTwoTLAR</option>

                                            }
                                        }
                                    }
                                }

                            </select>

                            <span asp-validation-for="@Model.StepTwoId" class="text-alert"></span>
                        </div>
                        <div class="col-lg-12" id="itemQuaintityId">
                            <div>
                                <label for="@Model.Quantity" class="form-label">@sharedResource["Quantity"]</label>
                                <input type="number" min="1" asp-for="@Model.Quantity" id="company_name-field" class="form-control" placeholder="@sharedResource["Enter Quantity"]" />
                                <span asp-validation-for="@Model.Quantity" class="text-danger"></span>
                            </div>
                        </div>
                       
                    </div>
                    <!--end row-->
                </div>
         
                <div class="modal-footer">
                    <div class="hstack gap-2 justify-content-end">
                        <button type="button" class="btn btn-light" data-bs-dismiss="modal">@sharedResource["Close"]</button>
                        <button class="btn btn-success" id="add-btn">@sharedResource["Add SubProduct"]</button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>

Areas/Store/Pages/ManageItem/_EditPopup.cshtml
@model Jovera.Models.Item

<div class="modal fade" id="showEditModal" tabindex="-1"
     aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header bg-light p-3">
                <h5 class="modal-title" id="exampleModalLabel"></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"
                        aria-label="Close" id="close-modal"></button>
            </div>

            <form asp-area="Store" asp-page="/ManageItem/ProductDetails" asp-route-itemId="@Model.ItemId" asp-page-handler="UpdateItemQuantity" enctype="multipart/form-data">
                <div class="modal-body">

                    <input value="@Model.ItemId" type="hidden" id="EditHiddenItemId" />

                    <div class="row g-3">
                      
                        <!--end col-->
                        <div class="col-lg-12">
                            <div>
                                <label for="@Model.Quantity"
                                       class="form-label">@sharedResource["Quantity"]</label>
                                <input type="text" asp-for="@Model.Quantity" id="EditQuantityId"
                                       class="form-control"
                                       placeholder="@sharedResource["Enter Quantity"]" required />
                            </div>
                        </div>

                    </div>
                    <!--end row-->
                </div>
                <div class="modal-footer">
                    <div class="hstack gap-2 justify-content-end">
                        <button type="button" class="btn btn-light"
                                data-bs-dismiss="modal">
                            @sharedResource["Close"]
                        </button>
                        <button type="submit" class="btn btn-success"
                                id="add-btn">
                            @sharedResource["Update Product Quantity"]
                        </button>

                    </div>
                </div>
            </form>
        </div>
    </div>
</div>